-- Generated by scripts/hypr2lua.
-- Source: omarchy-miasma-theme/hyprland.conf

local activeBorderColorGreen = "rgb(78824b)"
local activeBorderColorDark = "rgb(3c4125)"

hl.config({
  general = {
    col = {
      active_border = {
        colors = { activeBorderColorGreen, activeBorderColorDark },
        angle = 35,
      },
    },
  },
  group = {
    col = {
      border_active = {
        colors = { activeBorderColorGreen, activeBorderColorDark },
        angle = 35,
      },
    },
  },
  decoration = {
    shadow = {
      enabled = true,
      range = 10,
      render_power = 3,
      color = "rgba(0,0,0,0.6)",
      offset = "2 2",
    },
  },
  animations = {
    enabled = true,
  },
})

hl.curve("miasma", { type = "bezier", points = { { 0.55, 0.02 }, { 0.38, 0.98 } } })
hl.curve("fogbank", { type = "bezier", points = { { 0.70, 0.01 }, { 0.30, 1.00 } } })
hl.curve("toxic", { type = "bezier", points = { { 0.85, 0.00 }, { 0.25, 1.00 } } })

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 4,
  bezier = "miasma",
})
hl.animation({
  leaf = "windowsIn",
  enabled = false,
  speed = 0,
  bezier = "default",
})
hl.animation({
  leaf = "windowsOut",
  enabled = false,
  speed = 0,
  bezier = "default",
})
hl.animation({
  leaf = "windowsMove",
  enabled = true,
  speed = 3,
  bezier = "miasma",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 4,
  bezier = "fogbank",
})
hl.animation({
  leaf = "fadeIn",
  enabled = true,
  speed = 4,
  bezier = "fogbank",
})
hl.animation({
  leaf = "fadeOut",
  enabled = true,
  speed = 3,
  bezier = "fogbank",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 3,
  bezier = "fogbank",
  style = "fade",
})
