#                                                                                                             
#                                                                                                             
#                                                 @@@@@@@@@@@@@@                                              
#                                 @@@@@@@@@@@@@@@@@@          @@@@@@@@@@@@@@@                                 
#                            @@@@@@@@@@@@@      @@              @@      @@@@@@@@@@@@@                         
#                       @@@@@     @@@@        @@                  @@        @@@@     @@@@@                    
#                   @@@        @@@          @@                      @@         @@@        @@@                 
#                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              
#            @@@@          @@             @@                          @@            @@         @@@@           
#          @@@           @@              @@                            @@             @@          @@@         
#        @@@            @@               @@                            @@              @@           @@@       
#       @@                                                                                            @@      
#      @@                                                                                              @@     
#     @@            @@           @@         @@  @@           @@   @@@@@@@@@@@@  @@@        @@           @@    
#    @@             @@           @@         @@  @@@@       @@@@  @@@@@@  @@@@@@ @@@@@      @@            @@   
#    @              @@           @@         @@  @@@@@     @@@@@  @@@@@    @@@@@ @@  @@@    @@             @   
#    @              @@           @@         @@  @@  @@@  @@@ @@  @@@@      @@@@ @@    @@@@ @@             @   
#    @              @@           @@         @@  @@   @@@@@@  @@  @@@@@    @@@@@ @@      @@@@@             @   
#    @              @@@@@@@@@@@@ \@@@@@@@@@@@/  @@    @@@@   @@   @@@@@@@@@@@@  @@        %@@             @   
#    @@                                                                                                  @@   
#     @@                                                                                                @@    
#      @@              @@                @@                            @@                @@            @@     
#        @@             @@               @@                            @@               @@           @@       
#          @@            @@               @@                          @@               @@          @@         
#            @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@           
#               @@@         @@@            @@                        @@            @@         @@@             
#                  @@@         @@           @@                      @@          @@@        @@@                
#                     @@@@@      @@@          @@                  @@         @@@      @@@@@                   
#                          @@@@@@    @@@        @@              @@        @@@   @@@@@@                        
#                               @@@@@@@@@@@@@@    @@          @@    @@@@@@@@@@@@@                             
#                                            @@@@@@@@@@@@@@@@@@@@@@@@                                         
#                                                                                                             
#                                              ＵＮＩＴＥＤ ＩＮ 𝙎𝙀𝙑𝙀𝙍𝘼𝙉𝘾𝙀                                            

# alacritty.toml
# By OldJobobo (https://github.com/OldJobobo)
# 

[window]
opacity=0.3

[colors]
transparent_background_colors = false

[colors.primary]
background = "#1b2d40"
foreground = "#d6e2ee"

[colors.normal]
black   = "#1b2d40"
red     = "#4d86b0"
green   = "#5e95bc"
yellow  = "#6fa4c9"
blue    = "#6fb8e3"
magenta = "#8bc9eb"
cyan    = "#b4e4f6"
white   = "#d6e2ee"

[colors.bright]
black   = "#4A6B80"
red     = "#73a6cb"
green   = "#86b7d8"
yellow  = "#9dcae5"
blue    = "#f2fcff"
magenta = "#b1d8ee"
cyan    = "#d1eef8"
white   = "#ffffff"

[colors.cursor]
text   = "#071018"
cursor = "#f2fcff"

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#
