-- Generated by scripts/hypr2lua.
-- Source: omarchy-lumon-theme/hyprland.conf

local activeBorderColor = "rgb(f2fcff)"
local activeShadowColor = "rgb(6fb8e3)"
local inactiveBorderColor = "rgba(30486099)"
local inactiveShadowColor = "rgba(30486077)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    gaps_in = 14,
    gaps_out = 28,
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
  },
  decoration = {
    rounding = 6,
    rounding_power = 7,
    blur = {
      enabled = true,
      size = 2,
      passes = 3,
      noise = 0.05,
    },
    shadow = {
      enabled = true,
      range = 16,
      render_power = 4,
      color = activeShadowColor,
      color_inactive = inactiveShadowColor,
    },
  },
})
